---
title: "Linie lotnicze Projekt 2022"
author: "Milosz Ksiazek"
date: "21 05 2022"
output: pdf_document
params:
  dbuser: 
    label: "Username"
    value: ""
    input: text
  dbpass: 
    label: "Password"
    value: ""
    input: password
---
Projekt przedstawiający polecenia wraz z wygenerowanymi tabelami z analizy bazy danych dotyczących
opóźnień połączeń lotniczych w USA w lipcu 2017 r.
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages("RPostgres")

library(DBI)
connection <- dbConnect(RPostgres::Postgres(),
                 dbname = "dwbd_flights", 
                 host = "psql.wmi.amu.edu.pl",
                 user    = params$dbuser,
                 password    = params$dbpass)

```
## Zadanie 1

Jakie było średnie opóźnienie przylotu?
``` {sql connection=connection}
SELECT avg(arr_delay_new) AS "avg_delay" 
FROM "Flight_delays";
```

## Zadanie 2

Jakie było maksymalne opóźnienie przylotu?
``` {sql connection=connection}
SELECT max(arr_delay_new) AS "max_delay" FROM "Flight_delays";
```
## Zadanie 3

Który lot miał największe opóźnienie przylotu?\
[przewoźnik, miasto wylotu, miasto przylotu, data lotu, opóźnienie]
``` {sql connection=connection}
SELECT carrier, origin_city_name, dest_city_name, fl_date, arr_delay_new 
FROM "Flight_delays" 
WHERE arr_delay_new = (SELECT max(arr_delay_new)  FROM "Flight_delays");

```
## Zadanie 4

Które dni tygodnia są najgorsze do podróżowania?\
[tabela zawierająca dla każdego dnia tygodnia średni czas opóźnienia]
``` {sql connection=connection}
SELECT weekday_name, avg(arr_delay_new)  AS average
FROM "Flight_delays" f
INNER JOIN "Weekdays" d ON f.day_of_week = d.weekday_id 
GROUP BY weekday_name
ORDER BY average desc;
```
## Zadanie 5

Które linie lotnicze latające z San Francisco (SFO) mają najmniejsze opóźnienia przylotu?\
[tabela zawierająca nazwę przewoźnika oraz średnie opóźnienie z jego wszystkich lotów]
``` {sql connection=connection}
SELECT airline_name, avg_delay from
(SELECT airline_id , avg(arr_delay_new) AS avg_delay
FROM "Flight_delays" 
GROUP BY airline_id ) AS all_avg
INNER JOIN "Airlines" USING (airline_id)
WHERE airline_id IN 
(SELECT DISTINCT(airline_id) FROM "Flight_delays" WHERE origin = 'SFO')
ORDER BY avg_delay DESC;
```
## Zadanie 6

Jaka część linii lotniczych ma regularne opóźnienia, tj. jej lot ma średnio co najmniej 10 min. opóźnienia?\
[tylko linie lotnicze występujące w tabeli `Flight_delays`]
``` {sql connection=connection}
SELECT cast(A.number_of_carriers_10 AS float)/CAST(B.number_of_carriers AS float) 
AS late_proportion
FROM
 (SELECT count(*) number_of_carriers_10 FROM (
SELECT carrier, avg(arr_delay_new) AS average
FROM "Flight_delays" 
GROUP BY carrier 
HAVING avg(arr_delay_new) >= 10) AS aa ) A,
(SELECT count(*) number_of_carriers 
FROM (SELECT DISTINCT(carrier) 
FROM "Flight_delays") AS bb) B;

```
## Zadanie 7

Jak opóźnienia wylotów wpływają na opóźnienia przylotów?\
[współczynnik korelacji Pearsona między czasem opóźnienia wylotów a czasem opóźnienia przylotów]
``` {sql connection=connection}
SELECT CORR(arr_delay_new, dep_delay_new) as Pearsons_r
FROM "Flight_delays" ;
```
``` {sql connection=connection}
SELECT (avg(arr_delay_new * dep_delay_new) - (avg(arr_delay_new) *
avg(dep_delay_new))) / (stddev(arr_delay_new) * stddev(dep_delay_new))
AS Pearsons_r
FROM "Flight_delays";
```
``` {sql connection=connection}
SELECT ((SUM(arr_delay_new * dep_delay_new) - (SUM(arr_delay_new) 
* SUM(dep_delay_new)) / COUNT(*)))
/ (SQRT(SUM(arr_delay_new * arr_delay_new) - (SUM(arr_delay_new) 
* SUM (arr_delay_new)) / COUNT(*))
* SQRT(SUM(dep_delay_new * dep_delay_new) - (SUM(dep_delay_new) 
* SUM(dep_delay_new)) / COUNT(*)))
AS Pearsons_r
FROM "Flight_delays";
```
## Zadanie 8

Która linia lotnicza miała największy wzrost (różnica) średniego opóźnienia przylotów w ostatnim tygodniu miesiąca, tj. między 1-23 a 24-31 lipca?\
[nazwa przewoźnika oraz wzrost]
``` {sql connection=connection}
SELECT * FROM 
(SELECT airline_name , delay_increase FROM "Airlines"
INNER JOIN 
(
SELECT  l.airline_id, average_last - average_first AS delay_increase 
FROM 
(SELECT airline_id, avg(arr_delay_new) AS average_first
FROM "Flight_delays" 
WHERE day_of_month <= 23
GROUP BY airline_id) AS f
INNER JOIN  
(SELECT airline_id, avg(arr_delay_new) AS average_last
FROM "Flight_delays" 
WHERE day_of_month >= 24
GROUP BY airline_id) AS l
ON f.airline_id = l.airline_id
ORDER BY delay_increase DESC) AS ids
USING (airline_id)) AS list
WHERE list.delay_increase = 
(SELECT max(delay_increase) 
FROM (SELECT airline_name, delay_increase FROM "Airlines"
INNER JOIN 
(
SELECT  l.airline_id, average_last - average_first AS delay_increase 
FROM 
(SELECT airline_id, avg(arr_delay_new) AS average_first
FROM "Flight_delays" 
WHERE day_of_month <= 23
GROUP BY airline_id) AS f
INNER JOIN  
(SELECT airline_id, avg(arr_delay_new) AS average_last
FROM "Flight_delays" 
WHERE day_of_month >= 24
GROUP BY airline_id) AS l
ON f.airline_id = l.airline_id
ORDER BY delay_increase DESC) AS ids
USING (airline_id)) AS wh);
```
## Zadanie 9

Które linie lotnicze latają zarówno na trasie SFO → PDX (Portland), jak i SFO → EUG (Eugene)?
``` {sql connection=connection}
SELECT airline_name FROM "Airlines" 
INNER join
(SELECT distinct(one.airline_id) from
(SELECT airline_id, origin, dest
FROM "Flight_delays" 
WHERE origin = 'SFO' AND(dest = 'PDX' OR dest = 'EUG')) AS one
INNER JOIN 
(SELECT DISTINCT airline_id, origin, dest
FROM "Flight_delays" 
WHERE origin = 'SFO' AND(dest = 'PDX' OR dest = 'EUG')) AS two
ON one.airline_id = two.airline_id 
AND one.dest <> two.dest) AS ids
USING (airline_id);
```
## Zadanie 10
Jak najszybciej dostać się z Chicago do Stanfordu, zakładając wylot po 14:00 czasu lokalnego?
[tabela zawierająca jako miejsce wylotu Midway (MDW) lub O'Hare (ORD), jako miejsce przylotu San Francisco (SFO), San Jose (SJC) lub Oakland (OAK) oraz średni czas opóźnienia przylotu dla wylotów po 14:00 czasu lokalnego (atrybut `crs_dep_time`); wyniki pogrupowane po miejscu wylotu i przylotu, posortowane malejąco]
``` {sql connection=connection}
SELECT origin, dest, avg(arr_delay_new) AS avg_delay
FROM "Flight_delays" 
WHERE (origin = 'MDW' OR origin = 'ORD') 
AND (dest = 'SFO' OR dest = 'OAK' OR dest = 'SJC') 
AND crs_dep_time > 1400
GROUP BY origin, dest
ORDER BY avg_delay DESC;
```
